services:
  app:
    image: node:20
    container_name: dartiflet-node
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3010:3010"
    environment:
      - NODE_ENV=production
      - NITRO_HOST=0.0.0.0
      - NITRO_PORT=3010
    command: >
      sh -c "npm install && npm run build && node .output/server/index.mjs"
    restart: always