name: dartiflet

services:
  app:
    build: 
      context: ../..
      dockerfile: .docker/dev/Dockerfile
    container_name: dartiflet-app-dev
    volumes:
      - ../..:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3010:3000"
    environment:
      - NODE_ENV=development
    restart: always