services:
  maintenance:
    build:
      context: ../..
      dockerfile: .docker/maintenance/Dockerfile
    container_name: dartiflet-app-maintenance
    ports:
      - "3010:80"
    restart: always
  app:
    build:
      context: ../..
      dockerfile: .docker/prod/Dockerfile
    container_name: dartiflet-app
    ports:
      - "3010:3000"
    environment:
      - NODE_ENV=production
    restart: always
    depends_on:
      - maintenance
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"] # Vérifie la santé de l'application
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s