name: dartiflet

services:
  # maintenance:
  #   build:
  #     context: ../..
  #     dockerfile: .docker/maintenance/Dockerfile
  #   container_name: dartiflet-app-maintenance
  #   ports:
  #     - "3010:80"
  #   restart: always
  app:
    build:
      context: ../..
      dockerfile: .docker/prod/Dockerfile
    container_name: dartiflet-app
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`dartiflet.guerroue.fr`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=letsencrypt"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=3000"
    networks:
      - traefik-net
    restart: unless-stopped

networks:
  traefik-net:
    external: true
