services:
  maintenance:
    build:
      context: ../..
      dockerfile: .docker/maintenance/Dockerfile
    container_name: dartiflet-app-maintenance
    ports:
      - "3010:80"
    restart: always
  app:
    build:
      context: ../..
      dockerfile: .docker/prod/Dockerfile
    container_name: dartiflet-app
    ports:
      - "3020:3000"
    environment:
      - NODE_ENV=production
    restart: always