name: Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
    
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      # Set up SSH for deployment
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add host to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts


      # Execute deployment commands on the server

      # docker compose down

      # docker compose up -d maintenance
      # docker compose build app

      # docker compose stop maintenance
      # docker compose up -d app
      - name: Check Docker versions
        run: |
          docker --version
          docker compose version
      - name: Deploy application
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << EOF
          cd /home/projects/dartiflet/
          
          git fetch origin main
          git reset --hard origin/main

          cd .docker/prod

          docker --version
          docker compose version

          docker compose up -d --buid

          EOF
